Updated to reference pass_phrase.sh
Python is no longer shipping with Mac OS starting with 12.3 
I have removed pass_phrase.py from my workflow and rewrote pass_phrase.sh

diff --git a/Rescue_Account_Password_Change b/Rescue_Account_Password_Change
--- a/Rescue_Account_Password_Change
+++ b/Rescue_Account_Password_Change
@@ -1,12 +1,21 @@
 #!/bin/bash
 
-## written by theadamcraig
-## updated 3/26/2021
-## Re-worked the account creation section of the script. The jamf policy no longer needs to create the account
-## variables changed. eliminated variable 7, old password is not necessary
+#################################################
+# RESCUE ACCOUNT MANAGEMENT for MAC
+#################################################
 
+## https://github.com/theadamcraig/jamf-scripts/
 
-##Based on script found at FOUND AT https://github.com/therealmacjeezy/Scripts/blob/master/LAPS%20for%20Mac/LAPSforMac.sh
+## VARIABLES THAT NEED UPDATED
+## Passphrase variables
+## Pass location variable
+## JSS URL
+
+## updated 2/24/2021 by theadamcraig
+## No longer uses python
+## heavily reworked by theadamcraig 3/25/2021
+## this creates the local account now so the account creation portion of the jamf policy is no longer necessary
+## Initially based on script found at https://github.com/therealmacjeezy/Scripts/blob/master/LAPS%20for%20Mac/LAPSforMac.sh
 
 ########### Parameters (Required) ###############
 # 4 - API Username String
@@ -15,18 +24,17 @@
 # 7 - Local Admin Username
 # 8 - Local Admin Password
 
-passLocation="/Library/Application Support/YourCompany/rescue"
+passLocation="/Library/Application Support/YOURCOMPANY/rescue"
 #get the filepath
 pathLocation=$(dirname "$passLocation")
 #make sure the filepath exists
 mkdir -p "$pathLocation"
-# locate the pythonscript
-pythonScript="$pathLocation/passphrase/pass_phrase.py"
-# check to see if python is installed. pass_phrase.py should work with python 2 or 3
-pythonCheck=$(python -V  2>&1)
+# locate the password change script
+passwordScript="$pathLocation/passphrase/pass_phrase.sh"
+# This is the new shell script version of the pass_phrase.py script.
 
-## if the passphrase PythonScript doesn't exist then install it
-if [[ ! -e "$pythonScript" ]] ; then
+## if the pass_phrase.sh passwordScript doesn't exist then install it
+if [[ ! -e "$passwordScript" ]] ; then
 	jamf policy -trigger installpassphrase
 fi
 sleep 5
@@ -38,16 +46,21 @@ udid=$(/usr/sbin/system_profiler SPHardwareDataType | /usr/bin/awk '/Hardware UU
 extAttName="\"RescuePassword\""
 
 ## If the passphrase script exists get the passphrase from there. Else do a random passphrase
-if [[ -e "$pythonScript" ]]  && [[ "$pythonCheck" == *"Python"* ]]; then
-	cd "$pathLocation/passphrase"
-	echo "Python Script installed. Python check passed == $pythonCheck"
-	newPass=$(python "$pythonScript" -s "" --min=4 --max=5 -L)
+if [[ -e "$passwordScript" ]] ; then
+	cd "$pathLocation/passphrase" || exit
+	echo "Password Script installed."
+	newPass=$(sh "$passwordScript" --min 3 --max 6)
 	echo "$newPass" > "$passLocation"
-	getPass=$(cat "$passLocation")	
+	rescuePass=$(cat "$passLocation")	
 else
-	echo "Python script missing, or python check failed == $pythonCheck"
+	echo "Password script missing."
 	newPass=$(env LC_CTYPE=C tr -dc "A-HJ-KM-Za-hj-km-z0-9" < /dev/urandom | head -c 24 > "$passLocation")
-	getPass=$(cat "$passLocation")
+	rescuePass=$(cat "$passLocation")
+fi
+
+if [[ -z "$rescuePass" ]] ; then
+	echo "failed to get password"
+	exit 1
 fi
 
 # Decrypt String
@@ -82,17 +95,17 @@ else
     rescueUser="$6"
 fi
 
-if [[ -z "$8" ]];then
+if [[ -z "$7" ]];then
 	echo "ERROR: LOCAL ADMIN USERNAME MISSING"
 	exit 1
 else
-	adminName="$8"
+	adminName="$7"
 fi
-if [[ -z "$9" ]];then
+if [[ -z "$8" ]];then
 	echo "ERROR: LOCAL ADMIN PASSWORD MISSING"
 	exit 1
 else
-	adminPass="$9"
+	adminPass="$8"
 fi
 
 #####################################################
@@ -100,7 +113,6 @@ fi
 ## Functions that the script will use
 #####################################################
 #####################################################
-
 
 userExists(){
 	local userToCheck="$1"
@@ -213,6 +225,7 @@ createUserAccount() {
 	local adminUserName="${4}"
 	local adminUserPass="${5}"
 	echo " "
+	echo " "
 	echo "Creating account using Jamf. to create home folder and suppress setup account."
 	jamf createAccount -username "$userShortName" -realname "$userFullName" -password "$userPassword" -admin -suppressSetupAssistant
 	sleep 1
@@ -225,6 +238,7 @@ createUserAccount() {
 	echo "deleting account using dscl, which should leave home folder in place"
 	dscl . delete "/Users/$userShortName"
 	sleep 1
+	
 	echo " "
 	echo "re-creating account using sysadminctl to make sure that filevault recovery mode access exists, and account has the same UID."
 	sysadminctl -addUser "$userShortName" -fullName "$userFullName" -password "$userPassword" -adminUser "$adminUserName" -adminPassword "$adminUserPass" -home "/Users/$userShortName" -UID "$userUID" -admin
@@ -235,13 +249,12 @@ createUserAccount() {
 	echo " "
 }
 
-
 addUserToFilevault() {
-	fvUser="${1}"
-	fvPass="${2}"
-	addUser="${3}"
-	addPass="${4}"
-	remove="${5:-false}"
+	local fvUser="${1}"
+	local fvPass="${2}"
+	local addUser="${3}"
+	local addPass="${4}"
+	local remove="${5:-false}"
 	if [[ "$remove" == "true" ]] ; then
 		fdesetup remove -user "$addUser"
 	fi
@@ -297,14 +310,18 @@ echo " "
 
 ## FIX rescue NOT EXIST
 if [[ "$rescueExists" == "false" ]] ; then
+	echo "$rescueUser does not exist. Creating account"
+	
 	createUserAccount "$rescueUser" "$rescueUser" "$rescuePass" "$adminName" "$adminPass"
 # 	userShortName="${1}"
 # 	userFullName="${2}"
 # 	userPassword="${3}"
 # 	adminUserName="${4}"
 # 	adminUserPass="${5}"
+	echo "adding $rescueUser icon"
 	jamf recon
 	sleep 1
+	jamf policy -trigger "${rescueUser}icon"
 	# update other checks
 	rescueExists=$(userExists "$rescueUser" )
 	rescueIsAdmin=$(userIsAdmin "$rescueUser" )
@@ -385,3 +402,5 @@ uploadCheck
 echo " "
 echo "Updating apfs preboot"
 diskutil apfs updatePreboot / >> /dev/null 2>&1 
+
+exit 0
