Rework of rescue account password change script. Variables changed, functions updated, creates the account on its own now.

diff --git a/Rescue_Account_Password_Change b/Rescue_Account_Password_Change
--- a/Rescue_Account_Password_Change
+++ b/Rescue_Account_Password_Change
@@ -1,20 +1,21 @@
 #!/bin/bash
 
-#################################################
-# LAPS for MAC
-#################################################
+## written by theadamcraig
+## updated 3/26/2021
+## Re-worked the account creation section of the script. The jamf policy no longer needs to create the account
+## variables changed. eliminated variable 7, old password is not necessary
 
-##FOUND AT https://github.com/therealmacjeezy/Scripts/blob/master/LAPS%20for%20Mac/LAPSforMac.sh
+
+##Based on script found at FOUND AT https://github.com/therealmacjeezy/Scripts/blob/master/LAPS%20for%20Mac/LAPSforMac.sh
 
 ########### Parameters (Required) ###############
 # 4 - API Username String
 # 5 - API Password String
 # 6 - Rescue Admin Username
-# 7 - Old Password (Required for first usage)
-# 8 - Local Admin Username
-# 9 - Local Admin Password
+# 7 - Local Admin Username
+# 8 - Local Admin Password
 
-passLocation="/Library/Application Support/COMPANYNAME/rescue"
+passLocation="/Library/Application Support/YourCompany/rescue"
 #get the filepath
 pathLocation=$(dirname "$passLocation")
 #make sure the filepath exists
@@ -55,6 +56,10 @@ DecryptString() {
 	echo "${1}" | /usr/bin/openssl enc -aes256 -d -a -A -S "${2}" -k "${3}"
 }
 
+#####################################################
+## VERIFY WE HAVE ALL THE VARIABLES THAT WE NEED
+#####################################################
+
 # Account Information
 if [[ -z "$4" ]]; then 
     echo "Error: API USER MISSING"
@@ -90,114 +95,262 @@ else
 	adminPass="$9"
 fi
 
+#####################################################
+#####################################################
+## Functions that the script will use
+#####################################################
+#####################################################
 
-# Verify local rescue account exists
-checkUser=$(dseditgroup -o checkmember -m $rescueUser localaccounts | awk '{ print $1 }')
- 
-if [[ "$checkUser" = "yes" ]];then
-    echo "$rescueUser is a local user"
-else
-    echo "ERROR: $rescueUser is not a local user! :( Exiting."
-    exit 1
-fi
 
-# Magic Below
-passwordCheck() {
-    passCheck=$(/usr/bin/dscl /Local/Default -authonly "$rescueUser" "$oldPass")
-    if [[ -z "$passCheck" ]]; then
-        echo "Continue"
-    else
-        echo "ERROR: Password is either old or unknown, checking EA"
-        oldPass=$(curl -s -f -u $apiUser:$apiPass -H "Accept: application/xml" $jssURL/JSSResource/computers/udid/$udid/subset/extension_attributes | xpath "//extension_attribute[name=$extAttName]" 2>&1 | awk -F'<value>|</value>' '{print $2}' | tail -1)
-        passCheck2=$(/usr/bin/dscl /Local/Default -authonly "$rescueUser" "$oldPass")
-            if [[ ! -z "$passCheck2" ]]; then
-                echo "ERROR: Password is unknown. Exiting"
-                echo "Either computer could not reach Jamf server. Or password on Jamf Server is wrong."
-                exit 1
-            fi
-    fi
+userExists(){
+	local userToCheck="$1"
+	# returns True if the user exists false if the user does not
+	local userCheck
+	userCheck=$(dscl . list /Users | grep "$userToCheck" | grep -v "_mbsetupuser" )
+	if [[ "$userCheck" == "$userToCheck" ]] ; then
+		local exists="true"
+	else
+		local exists="false"
+	fi
+	echo "$exists"
 }
 
-if [[ ! -z "$7" ]]; then
-	echo "$7"
-    oldPass="$7"
-   #passwordCheck
-else
-    oldPass=$(curl -s -f -u $apiUser:$apiPass -H "Accept: application/xml" $jssURL/JSSResource/computers/udid/$udid/subset/extension_attributes | xpath "//extension_attribute[name=$extAttName]" 2>&1 | awk -F'<value>|</value>' '{print $2}')
-    #passwordCheck
-fi
-
-genLAPS() {
-    /usr/sbin/sysadminctl -adminUser $adminName -adminPassword $adminPass -resetPasswordFor $rescueUser -newPassword $getPass
+passwordCorrect() {
+	#returns true if the user password is correct false if it is not
+	local userName="${1}"
+	local passWord="${2}"
+	local passCheck
+	passCheck=$(/usr/bin/dscl /Local/Default -authonly "$userName" "$passWord")
+	if [[ -z "$passCheck" ]]; then
+		local correct="true"
+	else
+		local correct="false"
+	fi
+	echo "$correct"
 }
 
-resetCheck() {
-    /usr/bin/dscl /Local/Default -authonly "$rescueUser" "$getPass"
-    echo "New Password works as: $getPass"    
+fileVaultUserAccess() {
+	# returns true if the user has filevault access. false if they do not
+	local userToCheck="$1"
+	if [[ $(fdesetup list | grep "$userToCheck") == *"$userToCheck"* ]] ; then
+		local fvAccess="true"
+	else
+		local fvAccess="false"
+	fi
+	echo "$fvAccess"
+}
+
+userIsAdmin(){
+	local userToCheck="$1"
+	if [[ $("/usr/sbin/dseditgroup" -o checkmember -m "$userToCheck" admin / 2>&1) =~ "yes" ]]; then
+		local admin="true"
+	else
+		local admin="false"
+	fi
+	echo "$admin"
+}
+
+secureTokenUserCheck() {
+	local userToCheck="$1"
+	if [[ $("/usr/sbin/sysadminctl" -secureTokenStatus "$userToCheck" 2>&1) =~ "ENABLED" ]]; then
+		userToken="true"
+	else
+		userToken="false"
+	fi
+	echo "$userToken"
+}
+
+addSecureToken() {
+	local tokenUser="$1"
+	local tokenUserPass="$2"
+	local addUser="$3"
+	local addUserPass="$4"
+	echo "adding token to $addUser with credentials from $tokenUser"
+	sysadminctl -adminUser "$tokenUser" -adminPassword "$tokenUserPass" -secureTokenOn "$addUser" -password "$addUserPass"
+	tokenAdded=$(secureTokenUserCheck "$addUser")
+	echo "Token Added to $addUser : $tokenAdded"
+	diskutil apfs listcryptousers /
 }
 
 setEAStatus() {
 
-echo "setting EA status"
+	echo "setting EA status"
 
-apiData="<computer><extension_attributes><extension_attribute><name>RescuePassword</name><type>String</type><input_type><type>Text Field</type></input_type><value>${getPass}</value></extension_attribute></extension_attributes></computer>"
-echo ${apiData}
+	apiData="<computer><extension_attributes><extension_attribute><name>RescuePassword</name><type>String</type><input_type><type>Text Field</type></input_type><value>${rescuePass}</value></extension_attribute></extension_attributes></computer>"
+	echo "${apiData}"
 
-fullURL="$jssURL/JSSResource/computers/udid/$udid/subset/extension_attributes"
-echo ${fullURL}
+	fullURL="$jssURL/JSSResource/computers/udid/$udid/subset/extension_attributes"
+	echo "${fullURL}"
 
-apiPost=$(curl -s -f -u $apiUser:"$apiPass" -X "PUT" ${fullURL} -H "Content-Type: application/xml" -H "Accept: application/xml" -d "${apiData}" 2>&1 )
+	apiPost=$(curl -s -f -u "$apiUser":"$apiPass" -X "PUT" "${fullURL}" -H "Content-Type: application/xml" -H "Accept: application/xml" -d "${apiData}" 2>&1 )
 
-/bin/echo ${apiPost}
+	/bin/echo "${apiPost}"
 
-#rm -f /tmp/pwlaps
 }
-
 
 uploadCheck() {
-echo "Checking Password"
-checkPass=$(curl -s -f -u $apiUser:"$apiPass" -H "Accept: application/xml" $jssURL/JSSResource/computers/udid/$udid/subset/extension_attributes | xpath "//extension_attribute[name=$extAttName]" 2>&1 | awk -F'<value>|</value>' '{print $2}')
-checkPass=`echo "$checkPass" | tr -d '\040\011\012\015'`
-echo "$checkPass"
-echo "getPass"
-echo "$getPass"
+	echo "Checking Password"
+	checkPass=$(curl -s -f -u "$apiUser":"$apiPass" -H "Accept: application/xml" $jssURL/JSSResource/computers/udid/"$udid"/subset/extension_attributes | xpath "//extension_attribute[name=$extAttName]" 2>&1 | awk -F'<value>|</value>' '{print $2}')
+	checkPass=$(echo "$checkPass" | tr -d '\040\011\012\015')
+	echo "$checkPass"
+	echo "rescuePass"
+	echo "$rescuePass"
 
-if [[ "$checkPass" == "$getPass" ]] ; then
-	echo "password uploaded successfully"
-	rm -f "$passLocation"
-else
-	echo "password failed to upload to jamf"
-	echo "trying again"
-	setEAStatus
-fi
+	if [[ "$checkPass" == "$rescuePass" ]] ; then
+		echo "password uploaded successfully"
+		rm -f "$passLocation"
+	else
+		echo "password failed to upload to jamf"
+		echo "trying again"
+		setEAStatus
+	fi
 }
 
-updateFV2() {
+addUserToFilevault() {
+	fvUser="${1}"
+	fvPass="${2}"
+	addUser="${3}"
+	addPass="${4}"
+	remove="${5:-false}"
+	if [[ "$remove" == "true" ]] ; then
+		fdesetup remove -user "$addUser"
+	fi
+#create the plist file:
+echo '<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<plist version="1.0">
+<dict>
+<key>Username</key>
+<string>'$fvUser'</string>
+<key>Password</key>
+<string>'$fvPass'</string>
+<key>AdditionalUsers</key>
+<array>
+	<dict>
+		<key>Username</key>
+		<string>'$addUser'</string>
+		<key>Password</key>
+		<string>'$addPass'</string>
+	</dict>
+</array>
+</dict>
+</plist>' > /tmp/fvenable.plist  ### you can place this file anywhere just adjust the fdesetup line below
 
-fdesetup remove -user $rescueUser
+	# now enable FileVault
+	fdesetup add -i < /tmp/fvenable.plist
 
-expect -c "
-spawn fdesetup add -usertoadd $rescueUser
-expect \"Enter the primary user name:\"
-send ${adminName}\r
-expect \"Enter the password for the user '$adminName':\"
-send ${adminPass}\r
-expect \"Enter the password for the added user '$rescueUser':\"
-send ${getPass}\r
-expect" 
-
-fdeList=`fdesetup list | grep $rescueUser`
-
-if [[ "$fdeList" == *"$rescueUser"* ]] ; then
-	echo "$rescueUser Added to FileVault successfully"
-else
-	echo "Adding $rescueUser to FV2 Failed"
-fi
-
+	rm -r /tmp/fvenable.plist
 }
 
-genLAPS
-resetCheck
+
+#############################################
+#############################################
+##DO THE THINGS
+#############################################
+#############################################
+
+rescueExists=$(userExists "$rescueUser" )
+rescueIsAdmin=$(userIsAdmin "$rescueUser" )
+rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
+rescueFV=$(fileVaultUserAccess "$rescueUser" )
+rescueToken=$(secureTokenUserCheck "$rescueUser" )
+
+echo " "
+echo "Rescue account checks:"
+echo "exists: $rescueExists"
+echo "admin: $rescueIsAdmin (we want this to be false)"
+echo "passCorrect: $rescuePassCorrect"
+echo "filevault: $rescueFV"
+echo "secureToken: $rescueToken"
+echo " "
+echo " "
+
+## FIX rescue NOT EXIST
+if [[ "$rescueExists" == "false" ]] ; then
+	echo "$rescueUser does not exist. Creating account"
+	sysadminctl -addUser "$rescueUser" -fullName "$rescueUser" -password "$rescuePass" -adminUser "$adminName" -adminPassword "$adminPass"
+	echo "adding $rescueUser icon"
+	jamf recon
+	sleep 1
+	jamf policy -trigger "${rescueUser}icon"
+
+	# update other checks
+	rescueExists=$(userExists "$rescueUser" )
+	rescueIsAdmin=$(userIsAdmin "$rescueUser" )
+	rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
+	rescueFV=$(fileVaultUserAccess "$rescueUser" )
+	rescueToken=$(secureTokenUserCheck "$rescueUser" )
+	if [[ "$rescueExists" == "false" ]] ; then 
+		echo "$rescueUser failed to create"
+		exit 1
+	fi
+fi
+
+## FIX rescue IS ADMIN
+if [[ "$rescueIsAdmin" == "true" ]] ; then
+	echo "$rescueUser is an admin. Demoting account"
+	/usr/sbin/dseditgroup -o edit -n /Local/Default -d "$rescueUser" -t "user" "admin"
+	sleep 1
+	rescueIsAdmin=$(userIsAdmin "$rescueUser" )
+	rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
+	rescueFV=$(fileVaultUserAccess "$rescueUser" )
+	rescueToken=$(secureTokenUserCheck "$rescueUser" )
+	if [[ "$rescueIsAdmin" == "true" ]] ; then 
+		echo "$rescueUser failed to demote"
+		exit 1
+	fi
+fi
+
+## FIX rescue INCORRECT PASSWORD
+if [[ "$rescuePassCorrect" == "false" ]] ; then
+	echo "$rescueUser password is incorrect. changing password"
+	/usr/sbin/sysadminctl -adminUser "$adminName" -adminPassword "$adminPass" -resetPasswordFor "$rescueUser" -newPassword "$rescuePass"
+	sleep 1
+	rescuePassCorrect=$(passwordCorrect "$rescueUser" "$rescuePass")
+	rescueFV=$(fileVaultUserAccess "$rescueUser" )
+	rescueToken=$(secureTokenUserCheck "$rescueUser" )
+	if [[ "$rescuePassCorrect" == "false" ]] ; then 
+		echo "$rescueUser failed to update password"
+		exit 1
+	fi
+fi
+
+if [[ "$rescueFV" == "false" ]] ; then
+	echo "$rescueUser failed FV access"
+	addUserToFilevault "$adminName" "$adminPass" "$rescueUser" "$rescuePass"
+	sleep 1
+	rescueFV=$(fileVaultUserAccess "$rescueUser" )
+	rescueToken=$(secureTokenUserCheck "$rescueUser" )
+	if [[ "$rescueFV" == "false" ]] ; then 
+		echo "$rescueUser failed to update filevault"
+		exit 1
+	fi
+fi
+
+if [[ "$rescueToken" == false ]] ; then
+	echo "$rescueUser missing secure token, adding"
+	addSecureToken "$adminName" "$adminPass" "$rescueUser" "$rescuePass"
+	sleep 1
+	rescueToken=$(secureTokenUserCheck "$rescueUser" )
+	if [[ "$rescueToken" == "false" ]] ; then 
+		echo "$rescueUser failed to update secure token"
+		exit 1
+	fi
+fi
+
+echo " "
+echo "Final Checks:"
+echo "exists: $rescueExists"
+echo "admin: $rescueIsAdmin (we want this to be false)"
+echo "passCorrect: $rescuePassCorrect"
+echo "filevault: $rescueFV"
+echo "secureToken: $rescueToken"
+echo " "
+echo " "
+
 setEAStatus
-updateFV2
 uploadCheck
+
+echo " "
+echo "Updating apfs preboot"
+diskutil apfs updatePreboot / >> /dev/null 2>&1 
