Removed Tell system events from prompts

diff --git a/Update_local_password_for_jamf_connect b/Update_local_password_for_jamf_connect
--- a/Update_local_password_for_jamf_connect
+++ b/Update_local_password_for_jamf_connect
@@ -1,18 +1,12 @@
-#!/bin/bash
-
-## last updated 3/22/2021
-## written by theadamcraig
-## https://github.com/theadamcraig/jamf-scripts/
-## script to fix jamf connect users who forgot their password and cannot use the local password sync option.
-## designed to be run from the rescue account
-## this was written as we were transitioning to jamf connect so it also verifies that the users have jamf connect and are no longer bound to AD.
-## In my testing this updated filevault passwords as well.
-
-
 
 adminName=$4
 adminPass=$5
 rescueUser="rescue"
+
+if [[ -z "$adminName" ]] || [[ -z "$adminPass" ]] ; then
+	echo "admin name or admin pass missing"
+	exit 1
+fi
 
 #Get logged in user
 
@@ -24,6 +18,7 @@ if [[ -z "$loggedInUser" ]] || [[  "$loggedInUser" == 'root' ]] || [[ "$loggedIn
 else
 	echo "loggedInUser is $loggedInUser"
 fi
+loggedInUID=$(id -u "$loggedInUser")
 
 if [[ "$loggedInUser"  == "$adminName" ]] ; then
 	PROCEED="button returned:Yes"
@@ -43,11 +38,17 @@ fi
 
 
 #### SET UP DISPLAY DIALOG FUNCTION
+#### SET UP DISPLAY DIALOG FUNCTION
 DisplayDialog(){
 	local dialogText="$1"
-	echo "Display Dialog: $dialogText"
-	cmd="Tell app \"System Events\" to display dialog \"$dialogText\""
-	/usr/bin/osascript -e "$cmd"
+	echo "$dialogText"
+	#Log "Display Dialog: $dialogText"
+	cmd="display dialog \"$dialogText\" buttons {\"Continue\"} default button 1 giving up after 180"
+	if [[ -z "$loggedInUID" ]] || [[ -z "$loggedInUser" ]] ; then 
+		/usr/bin/osascript -e "$cmd"
+	else
+		/bin/launchctl asuser "$loggedInUID" sudo -iu "$loggedInUser" /usr/bin/osascript -e "$cmd"
+	fi
 }
 
 
@@ -101,13 +102,11 @@ else
 fi
 
 
+#
 ## get username to change
 echo "prompting user for Account Username"
-userName=$(/usr/bin/osascript<<END
-tell application "System Events"
-activate
-set the answer to text returned of (display dialog "Enter the username whose password you want to change:" default answer "" buttons {"Continue"} default button 1)
-end tell
+userName=$(/bin/launchctl asuser "$loggedInUID" sudo -iu "$loggedInUser" /usr/bin/osascript<<END
+text returned of (display dialog "Enter the username whose password you want to change:" default answer "" buttons {"Continue"} default button 1 giving up after 60 )
 END
 )
 
@@ -134,20 +133,14 @@ fi
 
 
 echo "prompting user for Account Password"
-userPass=$(/usr/bin/osascript<<END
-tell application "System Events"
-activate
-set the answer to text returned of (display dialog "Enter $userName's new password that matches AD." default answer "" buttons {"Continue"} default button 1)
-end tell
+userPass=$(/bin/launchctl asuser "$loggedInUID" sudo -iu "$loggedInUser" /usr/bin/osascript<<END
+text returned of (display dialog "Enter $userName's new password that matches AD." default answer "" buttons {"Continue"} default button 1 giving up after 60 )
 END
 )
 
 echo "prompting user for Account Password"
-verifyPass=$(/usr/bin/osascript<<END
-tell application "System Events"
-activate
-set the answer to text returned of (display dialog "Verify $userName's new password." default answer "" buttons {"Continue"} default button 1)
-end tell
+verifyPass=$(/bin/launchctl asuser "$loggedInUID" sudo -iu "$loggedInUser" /usr/bin/osascript<<END
+text returned of (display dialog "Verify $userName's new password." default answer "" buttons {"Continue"} default button 1 giving up after 60 )
 END
 )
 
@@ -177,7 +170,6 @@ userPassCheck=$(/usr/bin/dscl /Local/Default -authonly "$userName" "$userPass")
 if [[ -z "$userPassCheck" ]]; then
 	echo "Continue"
 	DisplayDialog "Password Change Successful"
-  exit 0
 else
 	echo "user Password not set correctly"
 	DisplayDialog "Password Change Failed"
